/*
  # Create campuses table

  1. New Tables
    - `campuses`
      - `id` (bigint, primary key)
      - `name` (text)
      - `address` (text)
      - `city` (text)
      - `latitude` (double precision)
      - `longitude` (double precision)
      - `image` (text)
      - `created_at` (timestamptz)
      - `updated_at` (timestamptz)

  2. Security
    - Enable RLS on `campuses` table
    - Add policy for public read access since campus data should be viewable by all users
*/

CREATE TABLE IF NOT EXISTS campuses (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL,
  address text NOT NULL,
  city text NOT NULL,
  latitude double precision NOT NULL,
  longitude double precision NOT NULL,
  image text NOT NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Enable Row Level Security
ALTER TABLE campuses ENABLE ROW LEVEL SECURITY;

-- Create policy to allow public read access
CREATE POLICY "Allow public read access"
  ON campuses
  FOR SELECT
  TO public
  USING (true);

-- Insert sample data
INSERT INTO campuses (name, address, city, latitude, longitude, image) VALUES
  ('BINUS Anggrek Campus', 'Jl. Kebon Jeruk Raya No. 27, Kebon Jeruk', 'Jakarta', -6.201820, 106.782352, '/images/binus1.jpg'),
  ('BINUS Syahdan Campus', 'Jl. K.H. Syahdan No. 9, Palmerah', 'Jakarta', -6.200462, 106.785102, '/images/binus2.jpg'),
  ('BINUS Alam Sutera Campus', 'Jl. Jalur Sutera Barat Kav. 21, Alam Sutera', 'Tangerang', -6.224335, 106.649177, '/images/binus3.jpg'),
  ('BINUS Bandung Campus', 'Jl. Pasir Kaliki No. 25-27, Cicendo', 'Bandung', -6.914744, 107.602680, '/images/binus4.jpg'),
  ('BINUS Bekasi Campus', 'Summarecon Bekasi, Jl. Boulevard Ahmad Yani Blok M', 'Bekasi', -6.226107, 107.000183, '/images/binus5.jpg'),
  ('BINUS Kijang Campus', 'Jl. Kemanggisan Ilir III No.45, Kemanggisan', 'Jakarta', -6.226107, 106.800183, '/images/binus6.jpg);

  